### PR TITLE
Allow labeling of walls

### PR DESCRIPTION
**Pull request by MrShark**
Add a parameter label to rectangularWall() that
is rendered in red to identify parts, it is not ment
to be cut or etched

Added labels to the OttoBody as an example of the API

### CODE REVIEW

**Comment by florianfesti** [comment]
This is a really great idea and a nice prove of concept. For rolling this out through the whole of Boxes.py we need to refine this a bit further.

I would probably move the actual rendering of the label move down into Boxes.move(). It knows the dimension of the parts and can make smarter decisions on where, how and whether to place the label. It would also make it easier to add labels to other parts.

Next (rather minor) thing is surrounding all the labels with `_( )` to they get picked up for translation.

At last we probably want a global switch to enable or disable the labels.

**Comment by MrShark** [comment]
Thanks! I tried to implement your suggestions. 
I don't fully understand the rendering model, so there is no smarter placement of the labels :-)
I also added a label parameter to some more wall types and tested them very slightly, the placement is not perfect but it gives a hint.

I'm also thinking of adding a section something like this into the documentation:

**Colors**
The generated files uses the following color conventions:

**Black**  The outer edges of a part
**Blue**  Inner edges of a part
**Red**  Comments or help lines that are not ment to be cut or etched
**Green**   Etchings  
Normaly you will cut things in the order: Green, Blue, Black. If other colors are present, the meaning should be obvious.

I don't think there are any etchings yet but it might come, have I made the right asumptions?

**Comment by MrShark** [comment]
Rebased the branch to master and squashed and split the changes to be one for the interface and one demoing the interface on Ottobody

**Comment by florianfesti** [comment]
I was just about to ask...

All labels should be wrapped in `_()` though. This not only marks them for translation but it also translates them (given someone actually added a translation for the current language). So even duplicates should be wrapped.

**Comment by florianfesti** [comment]
Another minor nitpick. The option should be `labels` and be `True` by default. Why making no difference functionality wise people are bad with negations and they should though be avoided in user interfaces (where possible).

**Comment by florianfesti** [comment]
The drawing of the label text is not happening at the right place. This may work for parts like the rectangularWall, that ends in the bottom left corner. But there is no guarantee on where the cursor is at that point.
Move the drawing command to the end of the `if not before:` block (line 1137). There we know that the part was actually drawn and the cursor is restored to the bottom left corner by `self.ctx.restore()`.

**Comment by florianfesti** [comment]
OK, just did those changes myself.

Text is now centered on the part. For very small parts we could decrease the font size. But may be I postpone this until it becomes an actual issue.

Anyway, thanks for your work. Now someone needs to label the about thousand parts in the ~120 generators there are...

**Pull request closed without merging**
