### PR TITLE
Add installation instructions for macOS

### PR DESCRIPTION
**Pull request by muellermartin**

### CODE REVIEW

**Comment by algernon71** [comment]
Thanks!

Now I can install successfully! :-) 

Or so it seems at least, but the Inkscape extension seems a bit broken?

The submenus under each category is empty or does not even show up?

screenshot 2019-02-28 at 00 24 02

**Comment by muellermartin** [comment]
You're welcome :)

Are all menus broken? For me the `Misc` menu works as all others do:

Inkscape screenshot of Boxes.py extension and its sub-menus

How did you install the inkscape plugin? Via `./setup.py install`? Maybe the menus you see are leftovers from previous (faulty) installation attempts?

**Comment by algernon71** [comment]
Ah, I wiped all the extensions and re-installed boxes, now they showed up!

Could have been some old garbage from the previous (non-brew) Inkscape install...

However now when I try to run one of the generators I get another error in Inkscape:
Traceback (most recent call last):
  File "/Users/kent/.config/inkscape/extensions/boxes", line 107, in <module>
    main()
  File "/Users/kent/.config/inkscape/extensions/boxes", line 47, in main
    run_generator(name, sys.argv[2:])
  File "/Users/kent/.config/inkscape/extensions/boxes", line 73, in run_generator
    box.close()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/boxes-0.1-py3.7.egg/boxes/__init__.py", line 594, in close
    svgutil.svgMerge(self.output, self.inkscapefile, out)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/boxes-0.1-py3.7.egg/boxes/svgutil.py", line 144, in svgMerge
    from lxml import etree as et
ImportError: dlopen(/Applications/Inkscape.app/Contents/Resources/lib/python2.7/site-packages/lxml/etree.so, 2): Symbol not found: _PyBaseString_Type
  Referenced from: /Applications/Inkscape.app/Contents/Resources/lib/python2.7/site-packages/lxml/etree.so
  Expected in: flat namespace
 in /Applications/Inkscape.app/Contents/Resources/lib/python2.7/site-packages/lxml/etree.so

And nothing happens...

**Comment by muellermartin** [comment]
Ah, yeah totally forgot to mention that, oopsie.

Inkscape on macOS ships its own version of Python 2.7 (without lxml).

My current workaround is a bit hacky, but works:

Quit Inkscape if it's running and open the file `/Applications/Inkscape.app/Contents/Resources/bin/inkscape` in a text editor (it's a shell script that launches the actual Inkscape binary). There, line 79 should look like this:

```
export PYTHONPATH="$TOP/lib/python$PYTHON_VERS/site-packages/"
```

Simply comment out this line, by putting a `#` in front of the line, so it looks like:

```
#export PYTHONPATH="$TOP/lib/python$PYTHON_VERS/site-packages/"
```

This should make Inkscape use Python from Homebrew.

Note, that this might break other plugins, but in this case you can simply change the line back and restart Inkscape. Did I mention this approach is a bit hacky?

**Comment by algernon71** [comment]
Ok, now it seems to be working :-)

A question: does the inkscape plugin offer more options than the web based generators?
It does seem like they have quite a few more...?

**Comment by muellermartin** [comment]
Nice to hear :) Probably I should add this workaround to the macOS guide then.

Regarding your question: I'm sure @florianfesti can answer this best ;)

**Comment by florianfesti** [comment]
Not quite sure what you mean by more options. Inkscape and the Web interface should offer the same functionality. There are a few generators that are disabled in the web interface (by setting webinterface = False) and might not get filtered out in the Inkscape plugin.
If you are talking about the other tabs in the UI thay are avalable when clicking on the "* Settings" lines in the web UI which should unfold them.

**Comment by florianfesti** [comment]
Thanks for the instructions! Merged!

**Pull request merged**
