### PR TITLE
Adding "Grooved Edge"

### PR DESCRIPTION
**Pull request by MarcinZukowski**
This adds an edge type that contains grooves, with differing styles/widths/counts etc.
This could also replace the GrippingEdge I guess.

Added an example of how this could work in UnevenHeightBox. 

Some interesting (IMO) examples of what this can produce:

```
scripts/boxes UnevenHeightBox --edge_types zeee --x 60 --y 60 --lid=1 --lid_height=20 --height0=40 --height1=40 --height2=50 --height3=50 --reference=0

scripts/boxes UnevenHeightBox --Grooved_gap=0.2 --Grooved_arc_angle 90 --Grooved_width 0.2 --Grooved_margin=0.2 --Grooved_style=softarc --reference 0 --edge_types zzez --x 60 --y 60 --lid=1 --lid_height 10 --height0=30 --height1=30 --height2=40 --height3=40

scripts/boxes UnevenHeightBox --Grooved_interleave 1 --Grooved_style triangle --Grooved_gap 0.2 --Grooved_tri_angle 45 --Grooved_width 0.1 --Grooved_margin 0.0 --edge_types zzzz --x 60 --y 60 --lid=1 --lid_height=20 --outside=0 --height0=40 --height1=30 --height2=45 --height3=40 --reference=0

scripts/boxes UnevenHeightBox --Grooved_style triangle --Grooved_gap 0.0 --Grooved_tri_angle 30 --Grooved_width 0.1 --Grooved_margin 0.0 --edge_types zzzz --x 60 --y 60 --lid=1 --lid_height=20 --outside=0 --height0=40 --height1=30 --height2=45 --height3=40 --reference=0
```

### CODE REVIEW

**Comment by MarcinZukowski** [comment]
@ffesti , this is a clean follow up to #240 .

I think I applied all your comments except of:
* splitting the "edge" part and its application - shout if you insist on it
* the "margins" - I'm still not sure what needs to be done here.

Let me know what else prevents this from being merged.

**Comment by florianfesti** [comment]
Ok, merged with minor tweaks.

I just now realized that there is no way to implement margin() for the GroovedEdge as the grooves depend on the edge length. Let's just ignore that for now...

**Comment by florianfesti** [comment]
Oh, and of course thanks for the work and tweaking!

**Comment by MarcinZukowski** [comment]
Sure thing. And thanks for creating an amazing project!

**Pull request closed without merging**
