### PR TITLE
Flag to Enable Bed Bolts

### PR DESCRIPTION
**Pull request by xloem**
I enabled bed bolts. What is the origin of that term?

- made `NutHole.sizes` into global `HexSizes` and added shaft diameter values
- added non-metric values to `HexSizes`
- added flags `--bolts` and `--nut_dist` and parsed passed bolt strings
- enabled bed bolts in classes that use them, if `--bolts` is passed

EDIT:
Things that could be immediately done to improve this:
- note: the bed bolt setup has incomplete design; the old code may not reflect a good plan
- [ ] move `bolts` and `nut_dist` to i think `FingerJointSettings`
  - this may also make some `bedBoltSettings` redundant
- [ ] remove `if self.bolts` from generators. pass the d2 and d3 bolt policies and detect whether or not to use them in the edges.
- [ ] move `HexSizes` to its own module
- [ ] add a comment here so Florian finds the changes

### CODE REVIEW

**Comment by florianfesti** [comment]
First of all it is great someone is interested in this feature. I added this very early in the life of Boxes.py but never had any use of it myself. As such is is still very rudimentary and has many possible improvements. Also many details are missing a proper plan. So don't try too hard to understand what the code is trying to do.

As for your changes: Moving the bolt data to a global is a step in the right direction. I wonder if we even should move that into its own module.

I am not too keen on adding more global options. `bolts` and `nut_dist` could probably go into `FingerHoleSettings`.

Generators should not need to do `if self.bolts` but the edges should handle that. So the generator would just supply the number/patterns of bolts but not deal with the details. (The current code is fine to play a round and get a better idea how tings should work).

**Comment by florianfesti** [comment]
First of all it is great someone is interested in this feature. I added this very early in the life of Boxes.py but never had any use of it myself. As such is is still very rudimentary and has many possible improvements. Also many details are missing a proper plan. So don't try too hard to understand what the code is trying to do.

As for your changes: Moving the bolt data to a global is a step in the right direction. I wonder if we even should move that into its own module.

I am not too keen on adding more global options. `bolts` and `nut_dist` could probably go into `FingerHoleSettings`.

Generators should not need to do `if self.bolts` but the edges should handle that. So the generator would just supply the number/patterns of bolts but not deal with the details. (The current code is fine to play a round and get a better idea how tings should work).

**Comment by florianfesti** [comment]
Bed bolts is hardware to assemble beds and other furniture. It's a screw that typically goes through a corner post and is anchored in the side board with a nut embedded after some distance.

While this feature here uses "normal" machine screws they are used in the same way as bed bolts. If a native speaker has suggestions for a better name I am really not that attached.

**Comment by xloem** [comment]
I had heard of them as "T-bolts", although I get the impression that they aren't used much anymore.

**Comment by florianfesti** [comment]
If the parameters move to the FingerJointSettings may be just "bolts" is specific enough.

**Comment by florianfesti** [comment]
OK, added at least the patch with the imperial screw sizes. No point for that to rot forever.

**Comment by florianfesti** [comment]
Closing this PR as it needs updating. We still have #36 open.

**Pull request closed without merging**
