### PR TITLE
Add a generator for paintstands

### PR DESCRIPTION
**Pull request by MrShark**
A simple stackable paintstand, very much inspired by:
https://www.youtube.com/watch?v=6HJarJg1npk

### CODE REVIEW

**Comment by florianfesti** [comment]
Very nice! Also a very nice use of the already existing features! From my POV this is ready to be merged. I still have a few idea of things you may want to improve beforehand. If not just drop me a note and I'll hit the merge button.

Add yourself to the copyright notice

Adding a vertical wall connecting the two layers along the lengths would make the stand much stronger. Don't know if this is really needed. But after hearing all the talk about squaring stuff up in the video... Even having it for only a short length would keep the stand from racking side by side. Needs some extra code to not collide with the holes for the bottles, though.

You can add an option to use .hexHolesRectangle() to squeeze an additional row onto narrow paintstands.

**Comment by MrShark** [comment]
Thanks, I'm out of town for a week and I can't do patches, so just now so go ahead and decide.
I have cut a few stands and I don't think a wall is needed, but have an idea for a matching tray for keeping brushes and other things with sides. Perhaps adding sides and making the "hole part" optional could be something.
HexHolesRectangle sounds good, I have done it manually on some of my stands. Will look into it if you don't beat me to it 😁

**Comment by florianfesti** [comment]
Well, then let's get this in right now and add all the other features afterwards.

**Comment by florianfesti** [comment]
Rearranged the pieces a bit to make them better fit together.
Also added the hex holes.

**Pull request merged**
