### PR TITLE
Sample Images for FlexBox5, SideDoorHousing,Tetris

### PR DESCRIPTION
**Pull request by littleroblet**
This adds Samples Images for FlexBox5, SideDoorHousing, and Tetris
There is a second image for SideDoorHousing (I can add this to the generator as a second image in a separate commit) 

included samples.sha256

Please let me know if I have done anything incorrectly. It was my first time committing to this project.

### CODE REVIEW

**Comment by florianfesti** [comment]
This looks pretty good already. If you want you can put the main images through https://tinypng.com/ as was done with most other pictures and regenerate the thumbnails after wards. But I can also just merge now and to that later myself.

Should probably add that step to the CONSTRIBUTING file...

**Comment by littleroblet** [comment]
Up to you but I can give it a go tomorrow. :)

**Comment by littleroblet** [comment]
@florianfesti I have put the images through tinypng.com and added a new commit. 

Please let me know if my Pull Request is done wrong. I am still learning to use GIT/Github properly. One of the reasons I did not just upload the images to the ticket.

**Comment by florianfesti** [comment]
Looks good! merged!

**Pull request merged**
