### PR TITLE
Added option for dividers in display shelf model

### PR DESCRIPTION
**Pull request by patvdleer**
Added an option to add dividers in the shelves of the display shelf model. I have not yet extensively tested this yet. 

Afterthought:
It would be nice if I could make this from thinner material but the code doesn't seem to (easily) allow multiple thickness (or I'm overlooking something)

Examples, 100x100x100 box, (inside), thickness of 3.62 mm:

image

image

### CODE REVIEW

**Comment by patvdleer** [comment]
Laser is currently running but so far so good!

image

**Comment by florianfesti** [comment]
An bit more general variant could be replacing `x` by `sx` as is used in many trays or turn the `x` parameter into sections. See https://florianfesti.github.io/boxes/html/usermanual.html#section-parameters
That way the sections can have individual widths.

**Comment by florianfesti** [comment]
The current code looks like things won't fit if `front_wall_height` and `divider_wall_height` are not the same value as the finger joint of the dividers and the finger holes in the front won't match.

The case with lower dividers is easy to fix. But the interesting case is dividers that are higher. In this case using a CompoundEdge at the front with the lower part "f" and upper part "E" should do the trick.

Just using `front_wall_height` for the divider heights is an easier way out of this if you don't want to put too much more work into the change.

This is a very nice feature both ways.

**Comment by patvdleer** [comment]
> The current code looks like things won't fit if front_wall_height and divider_wall_height are not the same value as the finger joint of the dividers and the finger holes in the front won't match.

I did not consider that, I'll look into it.

In the mean time; I made the display for the (water based) square paint bottles of Revell. 

image

image

**Comment by patvdleer** [comment]
I removed the `divider_wall_height` option temporarily, I'll do a proper fix after some more testing.

**Comment by florianfesti** [comment]
Do you need any help? This is a very nice feature I'd like to see getting finished up and merged.

**Comment by patvdleer** [comment]
Ill fix it asap, got a little sidetracked.

**Comment by patvdleer** [comment]
I fixed 2 out of 3 but Im having some issues with the CompoundEdge for when the divider wall is higher than the front wall.

I think I need to do the following, is this correct?
1. determine the finger length
2. calculate the amount of fingers
3. create a list of the fingers and dimensions

```python
if self.divider_wall_height > self.front_wall_height:
    length = self.front_wall_height
    fingers = 2
    f_lengths = []
    edges_ = [
        "f",
        edges.CompoundEdge(self, "".join(["f" * fingers]), f_lengths),
        "e",
        "e"
    ]
```

**Comment by florianfesti** [comment]
No, that would be horrible. The Boxes API was written by a lazy person fora lazy person! You only need to do

```
edges_ = [
        "f",
        edges.CompoundEdge(self, "fe", [self.front_wall_height, self.divider_height - self.front_wall_height]),
        "e",
        "e"
    ]
```

It is only important that the `f` edge and the matching `F` edge or `fingerHoles` have the same length (and settings). The edges take care of the details and make sure they fit together.

**Comment by patvdleer** [comment]
image
image
image

**Comment by florianfesti** [comment]
Oh, sorry. This ofc has to be `"fE"` so the wall protrudes to the same level as the front wall.

**Comment by patvdleer** [comment]
So like this? It's fine by me either way, any preference? 

image

**Comment by florianfesti** [comment]
Currently I don't really have a preference. Both are just fine with me.

To me it looks like this is ready to be merged. I will probably change the num_dividers and replace it with x supporting sections (similar to the TypeTray but only in one direction). But I am fine with merging this now unless you want to try that yourself or want to do anything else first.

**Comment by patvdleer** [comment]
No I'm fine with the current state and I'm happy with my new storage rack.

**Comment by florianfesti** [comment]
OK, great. Squashed and merged.

**Pull request merged**
