### PR TITLE
feat: Gridfinite-base add pads

### PR DESCRIPTION
**Pull request by clemens-tolboom**
Let's not waste material by generate the pads together with the openings

### CODE REVIEW

**Comment by florianfesti** [comment]
Generally I like this change. I wonder if we can make it a bit more in line wit the other gridfinity generators.

* Have the locations of the feet engraved on the bottom
* May be just make the feet 2 smaller as the holes

I also wonder if we want offer a mode with less feet as there can be a lot of them. The normal gridfinity boxes only have 4 but they do not need to put their weight on the feet but are also supported by the grid. May be offer 4, 6, 8, 9, 16?

**Comment by florianfesti** [comment]
Also don't worry  about the CI. It's annoying but I can take care of it as soon as we are ready to merge the PR.

**Comment by florianfesti** [comment]
I also just realized that the feet wont work with anything but the "F" bottom_edge.

**Comment by clemens-tolboom** [comment]
> Have the locations of the feet engraved on the bottom

We do not need this as the pads/feet are used for the other GridFinity generator.

> May be just make the feet 2 smaller as the holes

That makes sense

> I also just realized that the feet wont work with anything but the "F" bottom_edge.

Not sure what you mean :-(

**Comment by florianfesti** [comment]
Ah, I thought you wanted to add the feet to the base itself. Sure, this makes a lot more sense.

**Comment by florianfesti** [comment]
OK, turned the parameter into a checkbox and made it "off" by default, so the output is unchanged and passes the CI (hopefully).

**Comment by clemens-tolboom** [comment]
Thanks :-)

**Pull request merged**
