### PR TITLE
LED Matrix

### PR DESCRIPTION
**Pull request by fidoriel**
This is a draft for a LED Matrix for those cheap Chinese ws2812b matrices.
Like on my other PR, I need to wait for a chance to cut it.

### CODE REVIEW

**Comment by florianfesti** [comment]
You may want to not indent the content of the `description` string. It is formatted with markdown and indentation is treated as pre-formatted text.

Don't worry about the CI failure. This is not your fault and I'll look into how to fix that independently of your PR.

**Comment by fidoriel** [comment]
I am new to the laser cutting game. Some things are more efficient, larger and look better if cutter. They promised they will have a cutter soon ;)

**Comment by fidoriel** [comment]
For some reason, not all images are shown

**Comment by fidoriel** [comment]
Everything is tested and fixes now. I am happy :)

**Comment by fidoriel** [comment]
@florianfesti did you find a solution to the typing error 

> Don't worry about the CI failure. This is not your fault and I'll look into how to fix that independently of your PR.

Did you find a solution or should I add a type ignore here?

**Comment by florianfesti** [comment]
OK, fixed CI failure. Added the thumbnail to the checksums file and squashed all the commits.

Thanks for your work! Enjoy your new laser cutter!

**Pull request merged**
